;(function($){$.fn.lt_trace=function(){var t_type='margin';if(lotterytype==3){t_type='same';}
$.extend({lt_trace_issue:0,lt_trace_money:0});var t_count=$.lt_issues.tomorrow.length;var t_nowpos=0;$($.lt_id_data.id_tra_alct).html(t_count);var htmllabel='<div id="button111" class="current">'+lot_lang.dec_s13+'</div><div id="button12">'+lot_lang.dec_s10+'</div><div id="button13">'+lot_lang.dec_s11+'</div>';if(lotterytype==0||lotterytype==2){var htmllabel='<ul class="threeTab clearfix"><li class="one"><a class="current" id="button111">利润追号</a></li><li class="two"><a id="button12">同倍追号</a></li><li class="three"><a id="button13">翻倍追号</a></li></ul>';}else if(lotterytype==3){var htmllabel='<ul class="twoTab clearfix"><li class="one"><a class="current" id="button12">同倍追号</a></li><li class="two"><a id="button13">翻倍追号</a></li></ul>';}
var htmltext='追号计划：&nbsp;<span id="lt_margin_html">'+lot_lang.dec_s14+'&nbsp;<input size="3" class="input02" name="lt_trace_times_margin" type="text" id="lt_trace_times_margin" value="1" />&nbsp;<select id="pix" style="float: none;"><option value="0">最低收益率</option><option value="1">全程累积收益</option></select>&nbsp;<input size="3" class="input02" style="width:60px;" name="lt_trace_margin" type="text" id="lt_trace_margin" value="50" />&nbsp;<span id="symbol">%</span>&nbsp;</span>';htmltext+='<span id="lt_sametime_html" style="display:none;">'+lot_lang.dec_s14+'&nbsp;<input size="3" name="lt_trace_times_same" type="text" class="input022" id="lt_trace_times_same" value="1" /></span>';htmltext+='<span id="lt_difftime_html" style="display:none;">'+lot_lang.dec_s17+'&nbsp;<input size="3" name="lt_trace_diff" type="text"  value="1" class="input02" id="lt_trace_diff" />&nbsp;'+lot_lang.dec_s18+'　'+lot_lang.dec_s2+''+lot_lang.dec_s19+' <input size="3" name="lt_trace_times_diff" type="text" id="lt_trace_times_diff" value="2" class="input02" /></span>';htmltext+=''+lot_lang.dec_s15+':&nbsp;<input size="3" name="lt_trace_count_input" type="text" id="lt_trace_count_input" class="input02" value="10" /><input size="3" type="hidden" id="lt_trace_money" name="lt_trace_money" value="0" />';$(htmllabel).appendTo($.lt_id_data.id_tra_label);$(htmltext).appendTo($.lt_id_data.id_tra_lhtml);$("#pix").change(function(){if($(this).val()==0){$("#symbol").html('%');$("#lt_trace_margin").attr('size',3);$("#lt_trace_issues_today").find("td[name='profitmargin[]']").css("display","block");$("#title_profitmargin").css("display","block");}else if($(this).val()==1){$("#symbol").html('元');$("#lt_trace_margin").attr('size',10);$("#lt_trace_issues_today").find("td[name='profitmargin[]']").css("display","none");$("#title_profitmargin").css("display","none");}});$('#button111').click(function(){if($("#pix").val()==0){$("#lt_trace_issues_today").find("td[name='profitmargin[]']").css("display","block");$("#title_profitmargin").css("display","block");}
if($(this).attr("class")!="temp"){$('#lt_margin_html').show();$('#lt_sametime_html').hide();$('#lt_difftime_html').hide();t_type='margin';$(this).attr("class","current");$('#button12').attr("class","");$('#button13').attr("class","");}});$('#button12').click(function(){$("#lt_trace_issues_today").find("td[name='profitmargin[]']").css("display","none");$("#title_profitmargin").css("display","none");if($(this).attr("class")!="temp"){$('#lt_margin_html').hide();$('#lt_sametime_html').show();$('#lt_difftime_html').hide();t_type='same';$(this).attr("class","current");$('#button111').attr("class","");$('#button13').attr("class","");}});if(t_type=='same'){$('#lt_margin_html').hide();$('#lt_sametime_html').show();$('#lt_difftime_html').hide();}
$('#button13').click(function(){$("#lt_trace_issues_today").find("td[name='profitmargin[]']").css("display","none");$("#title_profitmargin").css("display","none");if($(this).attr("class")!="temp"){$('#lt_margin_html').hide();$('#lt_sametime_html').hide();$('#lt_difftime_html').show();t_type='diff';$(this).attr("class","current");$('#button111').attr("class","");$('#button12').attr("class","");}});function upTraceCount(){$('#lt_trace_count').html($.lt_trace_issue);$('#lt_trace_hmoney').html(JsRound($.lt_trace_money,2,true));$('#lt_trace_money').val($.lt_trace_money);}
$("input",$($.lt_id_data.id_tra_lhtml)).keyup(function(){$(this).val(Number($(this).val().replace(/[^0-9]/g,"0")));});$("#lt_trace_qissueno").change(function(){var t=0;if($(this).val()=='all'){t=parseInt($($.lt_id_data.id_tra_alct).html(),10);}else{t=parseInt($(this).val(),10);}
t=isNaN(t)?0:t;$("#lt_trace_count_input").val(t);});var issueshtml='<table border="0" cellspacing="0" cellpadding="0" id="lt_trace_issues_today" class="formTable" width="100%">';var ii=0;$.each($.lt_issues.today,function(i,n){ii++;issueshtml+='<tr id="tr_trace_'+n.issue+'"><td width="10px" align="center"><input type="checkbox" name="lt_trace_issues[]" value="'+n.issue+'" /></td><td width="30px" align="center">'+ii+'</td><td width="120px" align="center">'+n.issue+'</td><td width="90px" align="center"><input style="width:60px" name="lt_trace_times_'+n.issue+'" type="text" class="input03" value="0" disabled/>'+lot_lang.dec_s2+'</td><td width="70px" align="center">'+lot_lang.dec_s20+'<span id="lt_trace_money_'+n.issue+'">0.00</span></td><td width="80px" align="center">'+lot_lang.dec_s20+'<span id="lt_trace_accumulatemoney_'+n.issue+'">0.00</span></td><td width="110px" align="center" name="currentprofit[]">'+lot_lang.dec_s20+'<span id="lt_trace_currentprofit_'+n.issue+'">0.00</span></td><td width="110px" align="center">'+lot_lang.dec_s20+'<span id="lt_trace_profit_'+n.issue+'">0.00</span></td><td width="80px" align="center" name="profitmargin[]"><span id="lt_trace_profitmargin_'+n.issue+'">0</span>%</td></tr>';});var t=$.lt_issues.tomorrow.length-$.lt_issues.today.length;if($.lt_issues.today.length==0){$("#lottery_today_current").html('-');$("#lottery_today_surplus").html('-');}else{$("#lottery_today_current").html(t+1);$("#lottery_today_surplus").html($.lt_issues.today.length-1);}
$.each($.lt_issues.tomorrow,function(i,n){if(i<t){ii++;issueshtml+='<tr id="tr_trace_'+n.issue+'"><td width="10px" align="center"><input type="checkbox" name="lt_trace_issues[]" value="'+n.issue+'" /></td><td width="30px" align="center">'+ii+'</td><td width="120px" align="center">'+n.issue+'</td><td width="90px" align="center"><input style="width:60px" name="lt_trace_times_'+n.issue+'" type="text" class="input03" value="0" disabled/>'+lot_lang.dec_s2+'</td><td width="70px" align="center">'+lot_lang.dec_s20+'<span id="lt_trace_money_'+n.issue+'">0.00</span></td><td width="80px" align="center">'+lot_lang.dec_s20+'<span id="lt_trace_accumulatemoney_'+n.issue+'">0.00</span></td><td width="110px" align="center" name="currentprofit[]">'+lot_lang.dec_s20+'<span id="lt_trace_currentprofit_'+n.issue+'">0.00</span></td><td width="110px" align="center">'+lot_lang.dec_s20+'<span id="lt_trace_profit_'+n.issue+'">0.00</span></td><td width="80px" align="center" name="profitmargin[]"><span id="lt_trace_profitmargin_'+n.issue+'">0</span>%</td></tr>';}});issueshtml+='</table>';$(issueshtml).appendTo($.lt_id_data.id_tra_issues);function changeIssueCheck(obj){var money=$.lt_trace_base;var $j=$(obj).closest("tr");if($(obj).attr("checked")=='checked'){$j.find("input[name^='lt_trace_times_']").val(1).attr("disabled",false).data("times",1);$j.find("span[id^='lt_trace_money_']").html(JsRound(money,2,true));$j.find("span[id^='lt_trace_accumulatemoney_']").html(JsRound(money,2,true));$j.find("span[id^='lt_trace_profit_']").html(JsRound((winmoney-money),2,true));$j.find("span[id^='lt_trace_currentprofit_']").html(JsRound((winmoney-money),2,true));$j.find("span[id^='lt_trace_profitmargin_']").html(JsRound(((winmoney-money)/money),2,true));$.lt_trace_issue++;$.lt_trace_money+=money;}else{var t=$j.find("input[name^='lt_trace_times_']").val();$j.find("input[name^='lt_trace_times_']").val(0).attr("disabled",true).data("times",0);$j.find("span[id^='lt_trace_money_']").html('0.00');$j.find("span[id^='lt_trace_accumulatemoney_']").html('0.00');$j.find("span[id^='lt_trace_profit_']").html('0.00');$j.find("span[id^='lt_trace_currentprofit_']").html('0.00');$j.find("span[id^='lt_trace_profitmargin_']").html('0');$.lt_trace_issue--;$.lt_trace_money-=money*parseInt(t,10);}
$.lt_trace_money=JsRound($.lt_trace_money,2);upTraceCount();};$("input[name^='lt_trace_times_']",$($.lt_id_data.id_tra_issues)).keyup(function(){var v=Number($(this).val().replace(/[^0-9]/g,"0"));$.lt_trace_money+=$.lt_trace_base*(v-$(this).data('times'));upTraceCount();$(this).val(v).data("times",v);$(this).closest("tr").find("span[id^='lt_trace_money_']").html(JsRound($.lt_trace_base*v,2,true));var prv_tr=$(this).parent().parent().prev();var temp=$.lt_trace_base*v;if(prv_tr.html()!=null){temp=$.lt_trace_base*v+parseFloat($(prv_tr).find("span[id^='lt_trace_accumulatemoney_']").html());}
$(this).closest("tr").find("span[id^='lt_trace_accumulatemoney_']").html(JsRound(temp,2,true));$(this).closest("tr").find("span[id^='lt_trace_profit_']").html(JsRound(winmoney*v-temp,2,true));});$("input[type='checkbox'][name^='lt_trace_issues']").click(function(){changeIssueCheck(this);});$("tr",$($.lt_id_data.id_tra_issues)).live("mouseover",function(){$(this).children().addClass("temp");}).live("mouseout",function(){if($(this).find(":checkbox").attr("checked")==false){$(this).children().removeClass("temp");}});var _initTraceByIssue=function(){var st_issue=$("#lt_issue_start").val();cleanTraceIssue();var isshow=false;var acount=0;var loop=0;var mins=t_nowpos;var maxe=t_nowpos;$.each($.lt_issues.today,function(i,n){loop++;if(isshow==false&&st_issue==n.issue){isshow=true;$($.lt_id_data.id_tra_today).click();}
if(isshow==false){acount++;maxe=Math.max(maxe,acount);}else{mins=Math.min(mins,acount);}
if(loop>=mins&&loop<=maxe){if(isshow==true){$("#tr_trace_"+n.issue,$($.lt_id_data.id_tra_issues)).show();}else{$("#tr_trace_"+n.issue,$($.lt_id_data.id_tra_issues)).hide();}}
if(loop>maxe){return false;}});$.each($.lt_issues.tomorrow,function(i,n){loop++;if(isshow==false&&st_issue==n.issue){isshow=true;$($.lt_id_data.id_tra_tom).click();}
if(isshow==false){acount++;maxe=Math.max(maxe,acount);}else{mins=Math.min(mins,acount);}
if(loop>=mins&&loop<=maxe){if(isshow==true){$("#tr_trace_"+n.issue,$($.lt_id_data.id_tra_issues)).show();}else{$("#tr_trace_"+n.issue,$($.lt_id_data.id_tra_issues)).hide();}}
if(loop>maxe){return false;}});t_count=$.lt_issues.tomorrow.length-acount;if($("#lt_trace_qissueno").val()=='all'){$("#lt_trace_count_input").val(t_count);}
t_nowpos=acount;$($.lt_id_data.id_tra_alct).html(t_count);$.lt_trace_issue=0;$.lt_trace_money=0;upTraceCount();};$("#lt_issue_start").change(function(){if($($.lt_id_data.id_tra_if).hasClass("clicked")==true){_initTraceByIssue();}});function zhuihao(){}
$(".close_betLayer").click(function(){$("#lt_trace_if_button").attr("checked",false);$(".ZH_bet_layerBox").hide();$($.lt_id_data.id_tra_stop).attr("disabled",true).attr("checked",false);$($.lt_id_data.id_tra_box1).hide();$($.lt_id_data.id_tra_box2).hide();$($.lt_id_data.id_tra_ifb).val('no');});$("#lt_trace_if_button_div").click(function(){$("#lt_trace_if_button").attr("checked",true);if($("#lt_trace_if_button").attr("checked")){if($.lt_total_nums<=0){$.alert(lot_lang.am_s7);$("#lt_trace_if_button").attr("checked",false);return;}
$($.lt_id_data.id_tra_stop).attr("disabled",false).attr("checked",true);$($.lt_id_data.id_tra_box1).show();$($.lt_id_data.id_tra_box2).show();$(".ZH_bet_layerBox").show();$($.lt_id_data.id_tra_ifb).val('yes');_initTraceByIssue();}else{$($.lt_id_data.id_tra_stop).attr("disabled",true).attr("checked",false);$($.lt_id_data.id_tra_box1).hide();$($.lt_id_data.id_tra_box2).hide();$(".ZH_bet_layerBox").hide();$($.lt_id_data.id_tra_ifb).val('no');}});$($.lt_id_data.id_tra_today).click(function(){if($(this).attr("class")!="selected"){$(this).attr("class","selected");$($.lt_id_data.id_tra_tom).attr("class","");$("#lt_trace_issues_today").show();$("#lt_trace_issues_tom").hide();}});$($.lt_id_data.id_tra_tom).click(function(){if($(this).attr("class")!="selected"){$(this).attr("class","selected");$($.lt_id_data.id_tra_today).attr("class","");$("#lt_trace_issues_today").hide();$("#lt_trace_issues_tom").show();}});var computeByMargin=function(s,m,b,o,p){s=s?parseInt(s,10):0;m=m?parseInt(m,10):0;b=b?Number(b):0;o=o?Number(o):0;p=p?Number(p):0;var t=0;if(b>0){if(m>0){t=Math.ceil(((m/100+1)*o)/(p-(b*(m/100+1))));}else{t=1;}
if(t<s){t=s;}}
return t;};var computeByMargin2=function(s,m,b,o,p){s=s?parseInt(s,10):0;m=m?parseInt(m,10):0;b=b?Number(b):0;o=o?Number(o):0;p=p?Number(p):0;var t=0;if(b>0){if(m>0){t=Math.ceil((m+o)/(p-b));}else{t=1;}
if(t<s){t=s;}}
return t;};var winmoney=0;$($.lt_id_data.id_tra_ok).click(function(){var c=parseInt($.lt_total_nums,10);if(c<=0){$.alert(lot_lang.am_s7);return false;}
var p=0;if(t_type=='margin'){var marmt=0;var marmd=0;var martype=0;$.each($('li',$($.lt_id_data.id_cf_content)),function(i,n){if(marmt!=0&&marmt!=$(n).data('data').methodid){martype=2;return false;}else{marmt=$(n).data('data').methodid;}
if(marmd!=0&&marmd!=$(n).data('data').modes){martype=3;return false;}else{marmd=$(n).data('data').modes;}
if($(n).data('data').prize<=0||$.inArray($(n).data('data').methodid,[371,373,375,377,379,381,383])>-1){martype=1;return false;}else{}});if(martype==1){$.alert(lot_lang.am_s32);return false;}else if(martype==2){$.alert(lot_lang.am_s31);return false;}else if(martype==3){$.alert(lot_lang.am_s33);return false;}}
p=0;var pmodel=$("#pmode").val();var stemp=-1;if(typeof(pmodel)!="undefined"){if(pmodel==$.lt_method_data.nfdprize.userdiffpoint){stemp=$.lt_method_data.nfdprize.defaultprize;}else{switch(pmodel){case'0':stemp=$.lt_method_data.nfdprize.levs;break;default:for(var jjj=0;jjj<$.lt_method_data.prizegroup.length;jjj++){if($.lt_method_data.prizegroup[jjj].point==pmodel)
{stemp=$.lt_method_data.prizegroup[jjj].prize;break;}}}}}
else{stemp=-1;}
var modes=parseInt($("select[name='lt_project_modes']").val(),10);stemp=Math.round((stemp*$.lt_method_data.modes[modes].rate)*1000)/1000;if(stemp<=0){return false;}
p=stemp;winmoney=p;var ic=parseInt($("#lt_trace_count_input").val(),10);ic=isNaN(ic)?0:ic;if(ic<=0){$.alert(lot_lang.am_s8);return false;}
if(ic>t_count){$.alert(lot_lang.am_s9);$("#lt_trace_count_input").val(t_count);return false;}
var times=parseInt($("#lt_trace_times_"+t_type).val(),10);times=isNaN(times)?0:times;if(times<=0){$.alert(lot_lang.am_s10);return false;}
times=isNaN(times)?0:times;var td=[];var tm=0;var msg='';if(t_type=='same'){var m=$.lt_trace_base*times;for(var i=0;i<ic;i++){tm+=m;var profit=(p*times-tm);var currentprofit=(p-m)*times;var profitmargin=0;td.push({times:times,money:m,accumulatemoney:tm,profit:profit,currentprofit:currentprofit,profitmargin:profitmargin});}
msg=lot_lang.am_s12.replace("[times]",times);}else if(t_type=='diff'){var d=parseInt($("#lt_trace_diff").val(),10);d=isNaN(d)?0:d;if(d<=0){$.alert(lot_lang.am_s11);return false;}
var m=$.lt_trace_base;var t=1;for(var i=0;i<ic;i++){if(i!=0&&(i%d)==0){t*=times;}
tm+=m*t;var profit=(p*t-tm);var currentprofit=(p-m)*t;var profitmargin=0;td.push({times:t,money:m*t,accumulatemoney:tm,profit:profit,currentprofit:currentprofit,profitmargin:profitmargin});}
msg=lot_lang.am_s13.replace("[step]",d).replace("[times]",times);}else if(t_type=='margin'){var e=parseInt($("#lt_trace_margin").val(),10);e=isNaN(e)?0:e;if(e<=0){$.alert(lot_lang.am_s30);return false;}
var m=$.lt_trace_base;if(e>=((p*100/m)-100)&&$("#pix").val()==0){$.alert(lot_lang.am_s30);return false;}
var t=0;for(var i=0;i<ic;i++){if($("#pix").val()==0){t=computeByMargin(times,e,m,tm,p);}else{t=computeByMargin2(times,e,m,tm,p);}
tm+=m*t;var profit=(p*t-tm);var currentprofit=(p-m)*t;var profitmargin=Math.round((profit/(tm))*100);td.push({times:t,money:m*t,accumulatemoney:tm,profit:profit,currentprofit:currentprofit,profitmargin:profitmargin});}
if($("#pix").val()==0){msg=lot_lang.am_s34.replace("[margin]",e).replace("[times]",times);}else{msg=lot_lang.am_s37.replace("[margin]",e).replace("[times]",times);}}
msg+=lot_lang.am_s14.replace("[count]",ic);$.confirm(msg,function(){cleanTraceIssue();var $s=$("tr:visible",$($.lt_id_data.id_tra_issues));for(i=0;i<ic;i++){var rowid=i;if(p*td[i].times>500000){$.alert('超过奖金限额');return false;}
$($s[rowid]).find(":checkbox").attr("checked",true);$($s[rowid]).find("input[name^='lt_trace_times_']").val(td[i].times).attr("disabled",false).data("times",td[i].times);$($s[rowid]).find("span[id^='lt_trace_money_']").html(JsRound(td[i].money,2,true));$($s[rowid]).find("span[id^='lt_trace_accumulatemoney_']").html(JsRound(td[i].accumulatemoney,2,true));$($s[rowid]).find("span[id^='lt_trace_profit_']").html(JsRound(td[i].profit,2,true));$($s[rowid]).find("span[id^='lt_trace_currentprofit_']").html(JsRound(td[i].currentprofit,2,true));$($s[rowid]).find("span[id^='lt_trace_profitmargin_']").html(td[i].profitmargin);$($s[rowid]).children().addClass("tmp");}
$.lt_trace_issue=ic;$.lt_trace_money=tm;upTraceCount();},'','',300);});}})(jQuery);function cancel(pid)
{if(confirm("真的要撤单吗?"))
{$.ajax({type:'GET',url:"./?controller=gameinfo&action=cancelgame",timeout:30000,data:"rMethod=1&id="+pid+"&d="+new Date().getTime(),success:function(datax){if(datax=='1'){betRecord(lotteryIds);alert("撤单成功");}else{alert("撤单失败");}}});}}
var lotteryIds="";function betRecord(lotteryId){lotteryIds=lotteryId;$.ajax({type:'POST',url:"./?controller=gameinfo&action=gamelistb&d="+new Date().getTime(),timeout:30000,data:"lotteryId="+lotteryId,success:function(datax){var data=eval(datax);var html="";for(var i=0;i<data.length;i++){var codehtml="";var sProjectCode="";var iscancel=data[i].iscancel;var isgetprize=data[i].isgetprize;var prizestatus=data[i].prizestatus;var statusText="未撤单";var statusText_1="&nbsp;";if(iscancel==0){if(isgetprize==0){statusText="<a href=\"javascript:cancel('"+data[i].projectid2+"');\">撤单</a>";statusText_1="未开奖";}else if(isgetprize==2){statusText_1="未中奖";}else if(isgetprize==1){if(prizestatus==0){statusText_1="未派奖";}else{statusText_1="已派奖";}}}else if(iscancel==1){statusText="已撤单";}else if(iscancel==2){statusText="已撤单";if(lotteryId==18){statusText_1=statusText;}}else if(iscancel==3){statusText="已撤单";}
html+="<li>"+"<span class=\"td01\"  style=\"width: 50%;\"><a href=\"javascript:void(0);\" class=\"show\" url-data=\"/?controller=gameinfo&action=main&tag=tagpage&id="+data[i].projectid2+"\">"+data[i].issue+"</a></span>"+"<span class=\"td02\">"+statusText_1+"</span>";if(lotteryId==18){html+="</li>";}else{html+="<span class=\"td03\">"+statusText+"</span>"+"</li>";}}
var alllength=10;var dlength=alllength-data.length;$("#lt_trace_issues_today_bet").html(html);if(lotteryId==18){$("#td01").html("奖期");$("#td03").css("display","none");$("#td01").css("width","110");}
$("#bodyhie",window.parent.document).css("height",$("body").height()+"px");$("#main",window.parent.document).css("height",$("body").height()+"px");$(".show").bind("click",function(){flagShow=$(this).parents("li").index();$(".lim_float_icon").hide();ftext=$(this).text();if(ftext.indexOf("在线客服")<0){$(".showmenu").attr("style","overflow: hidden;");$.layer({fix:true,title:$(this).attr("title"),type:2,offset:['',''],iframe:{src:$(this).attr("url-data")},border:[10,0.3,'#000',false],area:['800px','400px']});}});}});$.ajax({type:'POST',url:'./?controller=game&action=bonuscode&curmid=1',data:"lotteryid="+lotteryId+"&fivehd=5",success:function(datax){var data=eval(datax);var html="";var ssc="1,3,6,14,15,16,18,19,22,41";var klsf="26,28,29,31,36";var llx5="5,7,8,10,21,33,40,48";var three3d="11,12,17";var isssc=isinarr(ssc,cur_cz)>-1?1:0;var isllx5=isinarr(llx5,cur_cz)>-1?1:0;var is3d=isinarr(three3d,cur_cz)>-1?1:0;var isklsf=isinarr(klsf,cur_cz)>-1?1:0;var mid=0;mid=cur_methord.indexOf("前三")>-1?1:mid;mid=cur_methord.indexOf("后三")>-1?2:mid;mid=cur_methord.indexOf("前二")>-1?3:mid;mid=cur_methord.indexOf("后二")>-1?4:mid;mid=cur_methord.indexOf("四星")>-1?5:mid;mid=cur_methord.indexOf("中三")>-1?6:mid;mid=cur_methord.indexOf("前四")>-1?12:mid;mid=cur_methord.indexOf("前五")>-1?10:mid;var test=$(".lableclick").text();if(test.indexOf("前二")>-1){mid=3;}else if(test.indexOf("后二")>-1){mid=4;}
if(test.indexOf("前二"))
if(cur_methord.indexOf("不定胆")>-1){if(test.indexOf("前三")>-1){mid=1;}else if(test.indexOf("后三")>-1){mid=2;}else if(test.indexOf("中三")>-1){mid=6;}}
if(cur_methord.indexOf("猜冠军")>-1){mid=8;}else if(cur_methord.indexOf("猜冠亚军")>-1||test.indexOf("冠亚和值")>-1){mid=9;}
if(cur_methord==0&&(cur_cz==27||cur_cz==34))mid=8;var type="0";var tzjq="tzjq";if(cur_methord.indexOf("任选")<0&&test.indexOf("组")>-1&&test.indexOf("和值")<0&&test.indexOf("组合")<0&&test.indexOf("前二组选")<0&&test.indexOf("后二组选")<0){if(isllx5){type="zx";tzjq="tzjqxt";}}else if(test.indexOf("和值")>-1&&cur_methord.indexOf("任选")<0){type="hz";tzjq="tzjqxt";}else if(test.indexOf("大小单双")>-1&&cur_cz!=27&&cur_cz!=34){type="dxds";tzjq="tzjqxt";}
if(cur_methord.indexOf("大小")>-1&&(cur_cz==20||cur_cz==30||cur_cz==35)){type="jsksdx";tzjq="tzjqxt";}else if(cur_methord.indexOf("单双")>-1&&(cur_cz==20||cur_cz==30||cur_cz==35)){type="jsksds";tzjq="tzjqxt";}
if(test.indexOf("跨度")>-1){type="kd";tzjq="tzjqxt";}
cur_jqjq=data;var gaparr=getcodegap(mid);var str="";var tzxt="tzxt";if(isklsf)type="0";for(var i=0;i<data.length;i++){var issue=data[i].issue;if(cur_cz==11||cur_cz==12||cur_cz==18){issue=issue.substr(2);}else if(cur_cz!=27&&cur_cz!=34){issue=issue.substr(4);}
html+="<li><span class='"+tzjq+"'>"+issue+"</span><span>";var codearr=[];if(isinarr("5,7,8,10,27,48",cur_cz)>-1){codearr=data[i].code.split(" ");}else{codearr=data[i].code.split("");}
for(var j=0;j<codearr.length;j++){html+="<i class=\"code"+j;switch(mid){case 1:if(j<3){html+=" mark";}
break;case 2:if(j>1){html+=" mark";}
break;case 3:if(j<2){html+=" mark";}
break;case 4:if(isssc&&j>2){html+=" mark";}
if(!isssc&&j>0){html+=" mark";}
break;case 5:if(j>0){html+=" mark";}
break;case 6:if(j>0&&j<4){html+=" mark";}
break;case 8:if(j<1){html+=" mark";}
break;case 9:if(j<2){html+=" mark";}
break;case 10:if(j<5){html+=" mark";}
break;case 11:if(j>4){html+=" mark";}
break;case 12:if(j<4){html+=" mark";}
break;}
html+="\" >"+codearr[j]+"</i>";}
if(type=="0"){html+="</span><span class='tzxt' style='display:none;'>-</span></li>";}else{changeFormTitle(type);$("#tzxt").css("display","inline-block");str=getForm(cur_jqjq[i].code,type,gaparr);if(type=="dxds"){tzxt="tzxt dxds";html+="</span><span class='"+tzxt+"' style='display:inline-block;width:20%;'>"+str+"</span></li>";}else if((str=="组三"&&test=="组三")){html+="</span><span class='tzxt numberType' style='display:inline-block;'>"+str+"</span></li>";}else if(str=="组六"&&test=="组六"){html+="</span><span class='tzxt numberType' style='display:inline-block;'>"+str+"</span></li>";}else{html+="</span><span class='"+tzxt+"' style='display:inline-block;width:18%;'>"+str+"</span></li>";}}}
$("#WinnerNumList_div").html(html)}});}